name: Greetings

on: [push, workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    container:
      image: circleci/jruby:9.2.20.1-jdk17-node-browsers-legacy
    steps:
      - name: TEST-GHA
        run: |
           ls
           uname -r
