name: Greetings

on: [push, workflow_dispatch]

jobs:
  greeting:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: curl
        run: |
           ls
           uname -r
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: main
          key: ${{ runner.os }}-workspace        
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'          
