name: Greetings

on: [push, workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/amazonlinux/amazonlinux:2
    steps:
      - name: TEST-GHA
        run: |
           ls
           uname -r
