name: Greetings

on: [push, workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:2.0 
    steps:
      - name: TEST-GHA
        run: |
           ls
           uname -r
