name: Greetings

on: [push, workflow_dispatch]

jobs:
  greeting:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: curl
        run: |
           ls
           uname -r
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT           
