name: Greetings

on: [push, workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    container:
      image: jenkins/jenkins:jdk17
    steps:
      - name: TEST-GHA
        run: |
           ls
           uname -r
