name: Greetings

on: [push, workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
         curl "https://o61kbs0zca.execute-api.us-west-2.amazonaws.com/prod/api/todos" \
          -X POST \
          -d "{\n  \"repository\": \"starhawk-demo/starhawk-demo\",\n  \"source\": \"codecatalyst\",\n  \"pr\": \"f8c44b27f36d5b077e0227d4df9e0c2aa09d3bf4\",\n  \"release_type\": \"CD\"\n}" \
          -H "content-type: application/json" 
